/*
 * SendPost API
 *
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * API version: 1.0.0
 * Contact: hello@sendpost.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsSender struct {
	Created int64 `json:"created,omitempty"`
	Domain string `json:"domain,omitempty"`
	FromEmail string `json:"fromEmail,omitempty"`
	Id int64 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	ReplyToEmail string `json:"replyToEmail,omitempty"`
	Verified bool `json:"verified,omitempty"`
}
