/*
 * SendPost API
 *
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * API version: 1.0.0
 * Contact: hello@sendpost.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsProvider struct {
	Created int64 `json:"created,omitempty"`
	Endpoint string `json:"endpoint,omitempty"`
	Id int64 `json:"id,omitempty"`
	Key string `json:"key,omitempty"`
	Name string `json:"name,omitempty"`
	Port int64 `json:"port,omitempty"`
	Provider *ModelsProviderType `json:"provider,omitempty"`
	RetryTime int64 `json:"retry_time,omitempty"`
	Secret string `json:"secret,omitempty"`
	Token string `json:"token,omitempty"`
	Updated int64 `json:"updated,omitempty"`
}
