/*
 * SendPost API
 *
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * API version: 1.0.0
 * Contact: hello@sendpost.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsIncident struct {
	AssignedTo *ModelsMember `json:"assignedTo,omitempty"`
	Author *ModelsMember `json:"author,omitempty"`
	Closed int64 `json:"closed,omitempty"`
	Created int64 `json:"created,omitempty"`
	Description string `json:"description,omitempty"`
	Id int64 `json:"id,omitempty"`
	RelatedIP *ModelsIp `json:"relatedIP,omitempty"`
	RelatedSubAccount *ModelsSubAccount `json:"relatedSubAccount,omitempty"`
	Status *ModelsIncidentStatus `json:"status,omitempty"`
	Summary string `json:"summary,omitempty"`
	Tags []ModelsTag `json:"tags,omitempty"`
	Updated int64 `json:"updated,omitempty"`
}
