/*
 * SendPost API
 *
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * API version: 1.0.0
 * Contact: hello@sendpost.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsQEvent struct {
	AccountID int64 `json:"accountID,omitempty"`
	EventID string `json:"eventID,omitempty"`
	EventMetadata *ModelsEventMetadata `json:"eventMetadata,omitempty"`
	From string `json:"from,omitempty"`
	Groups *interface{} `json:"groups,omitempty"`
	IpID int64 `json:"ipID,omitempty"`
	MessageID string `json:"messageID,omitempty"`
	MessageType string `json:"messageType,omitempty"`
	SubAccountID int64 `json:"subAccountID,omitempty"`
	SubmittedAt int64 `json:"submittedAt,omitempty"`
	To string `json:"to,omitempty"`
	Type_ int64 `json:"type,omitempty"`
}
