/*
 * SendPost API
 *
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * API version: 1.0.0
 * Contact: hello@sendpost.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsBillingPortalSession struct {
	Created int64 `json:"created,omitempty"`
	Customer string `json:"customer,omitempty"`
	Id string `json:"id,omitempty"`
	Livemode bool `json:"livemode,omitempty"`
	Object string `json:"object,omitempty"`
	ReturnUrl string `json:"return_url,omitempty"`
	Url string `json:"url,omitempty"`
}
