/*
 * SendPost API
 *
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * API version: 1.0.0
 * Contact: hello@sendpost.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsWMessage struct {
	AccountID int64 `json:"AccountID,omitempty"`
	From string `json:"From,omitempty"`
	Groups *interface{} `json:"Groups,omitempty"`
	IPID int64 `json:"IPID,omitempty"`
	MessageType string `json:"MessageType,omitempty"`
	MessageUUID string `json:"MessageUUID,omitempty"`
	MockMessage bool `json:"MockMessage,omitempty"`
	MockTimeShift int64 `json:"MockTimeShift,omitempty"`
	SMTPCode int64 `json:"SMTPCode,omitempty"`
	SMTPDescription string `json:"SMTPDescription,omitempty"`
	SubAccountID int64 `json:"SubAccountID,omitempty"`
	SubmittedAt int64 `json:"SubmittedAt,omitempty"`
	To string `json:"To,omitempty"`
	Type_ *ModelsEventType `json:"Type,omitempty"`
}
