/*
 * SendPost API
 *
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * API version: 1.0.0
 * Contact: hello@sendpost.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsEIncident struct {
	AssignedTo *ModelsIeMember `json:"assignedTo,omitempty"`
	Author *ModelsIeMember `json:"author,omitempty"`
	Description string `json:"description,omitempty"`
	RelatedIP *ModelsIeip `json:"relatedIP,omitempty"`
	RelatedSubAccount *ModelsIeSubAccount `json:"relatedSubAccount,omitempty"`
	Status int64 `json:"status,omitempty"`
	Summary string `json:"summary,omitempty"`
	Tags []ModelsIeTag `json:"tags,omitempty"`
}
