/*
 * SendPost API
 *
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * API version: 1.0.0
 * Contact: hello@sendpost.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsQEmailMessage struct {
	AccountID int64 `json:"accountID,omitempty"`
	AmpBody string `json:"ampBody,omitempty"`
	Attempt int64 `json:"attempt,omitempty"`
	CustomFields *interface{} `json:"customFields,omitempty"`
	EmailType string `json:"emailType,omitempty"`
	From *ModelsFrom `json:"from,omitempty"`
	Groups *interface{} `json:"groups,omitempty"`
	Headers *interface{} `json:"headers,omitempty"`
	HtmlBody string `json:"htmlBody,omitempty"`
	IpID int64 `json:"ipID,omitempty"`
	IpPool string `json:"ipPool,omitempty"`
	LocalIP string `json:"localIP,omitempty"`
	MessageID string `json:"messageID,omitempty"`
	PreText string `json:"preText,omitempty"`
	PublicIP string `json:"publicIP,omitempty"`
	ReplyTo *ModelsReplyTo `json:"replyTo,omitempty"`
	SubAccountID int64 `json:"subAccountID,omitempty"`
	Subject string `json:"subject,omitempty"`
	SubmittedAt int64 `json:"submittedAt,omitempty"`
	TextBody string `json:"textBody,omitempty"`
	To *ModelsTo `json:"to,omitempty"`
	TrackClicks bool `json:"trackClicks,omitempty"`
	TrackOpens bool `json:"trackOpens,omitempty"`
}
