/*
 * SendPost API
 *
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * API version: 1.0.0
 * Contact: hello@sendpost.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsDomain struct {
	Created int64 `json:"created,omitempty"`
	Dkim *ModelsDnsRecord `json:"dkim,omitempty"`
	DkimConfig string `json:"dkimConfig,omitempty"`
	DkimVerified bool `json:"dkimVerified,omitempty"`
	Id int64 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	ReturnPath *ModelsDnsRecord `json:"returnPath,omitempty"`
	ReturnPathVerified bool `json:"returnPathVerified,omitempty"`
	Track *ModelsDnsRecord `json:"track,omitempty"`
	TrackVerified bool `json:"trackVerified,omitempty"`
	Verified bool `json:"verified,omitempty"`
}
