/*
 * SendPost API
 *
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * API version: 1.0.0
 * Contact: hello@sendpost.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsCertificateExtensions struct {
	AuthorityInfoAccess string `json:"authorityInfoAccess,omitempty"`
	AuthorityKeyIdentifier string `json:"authorityKeyIdentifier,omitempty"`
	BasicConstraints string `json:"basicConstraints,omitempty"`
	CertificatePolicies string `json:"certificatePolicies,omitempty"`
	CrlDistributionPoints string `json:"crlDistributionPoints,omitempty"`
	ExtendedKeyUsage string `json:"extendedKeyUsage,omitempty"`
	KeyUsage string `json:"keyUsage,omitempty"`
	SubjectKeyIdentifier string `json:"subjectKeyIdentifier,omitempty"`
}
