/*
 * SendPost API
 *
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * API version: 1.0.0
 * Contact: hello@sendpost.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsMember struct {
	CompanyName string `json:"companyName,omitempty"`
	Created int64 `json:"created,omitempty"`
	Email string `json:"email,omitempty"`
	Id int64 `json:"id,omitempty"`
	IsForbidden bool `json:"isForbidden,omitempty"`
	IsVerified bool `json:"isVerified,omitempty"`
	Name string `json:"name,omitempty"`
	OnboardQAnswered bool `json:"onboardQAnswered,omitempty"`
	PhoneNumber string `json:"phoneNumber,omitempty"`
	Url string `json:"url,omitempty"`
}
