/*
 * SendPost API
 *
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * API version: 1.0.0
 * Contact: hello@sendpost.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsEAccountMember struct {
	CompanyName string `json:"companyName,omitempty"`
	CurrentEmailServiceProvider string `json:"currentEmailServiceProvider,omitempty"`
	Industry string `json:"industry,omitempty"`
	LogoURL string `json:"logoURL,omitempty"`
	Name string `json:"name,omitempty"`
	OnboardCFinished bool `json:"onboardCFinished,omitempty"`
	OnboardQAnswered bool `json:"onboardQAnswered,omitempty"`
	PhoneNumber string `json:"phoneNumber,omitempty"`
	SendingVolumePerMonth string `json:"sendingVolumePerMonth,omitempty"`
	Uid string `json:"uid,omitempty"`
	VerifyEmail bool `json:"verifyEmail,omitempty"`
}
