/*
 * SendPost API
 *
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * API version: 1.0.0
 * Contact: hello@sendpost.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsDomainAge struct {
	DomainAgeFound bool `json:"domainAgeFound,omitempty"`
	DomainAgeInDays int32 `json:"domainAgeInDays,omitempty"`
	DomainAgeInMonths int32 `json:"domainAgeInMonths,omitempty"`
	DomainAgeInYears int32 `json:"domainAgeInYears,omitempty"`
	DomainCreationDate string `json:"domainCreationDate,omitempty"`
	DomainRegistered string `json:"domainRegistered,omitempty"`
	Host string `json:"host,omitempty"`
}
