/*
 * SendPost API
 *
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * API version: 1.0.0
 * Contact: hello@sendpost.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsIp struct {
	AolSettings string `json:"aolSettings,omitempty"`
	AutoWarmupEnabled bool `json:"autoWarmupEnabled,omitempty"`
	ComcastSettings string `json:"comcastSettings,omitempty"`
	Created int64 `json:"created,omitempty"`
	DefaultSettings string `json:"defaultSettings,omitempty"`
	GmailSettings string `json:"gmailSettings,omitempty"`
	GmxSettings string `json:"gmxSettings,omitempty"`
	IcloudSettings string `json:"icloudSettings,omitempty"`
	Id int64 `json:"id,omitempty"`
	InfraClassification string `json:"infraClassification,omitempty"`
	InfraMonitor bool `json:"infraMonitor,omitempty"`
	IpDomainWarmupStatus []ModelsIpDomainWarmupStatus `json:"ipDomainWarmupStatus,omitempty"`
	Labels []ModelsLabel `json:"labels,omitempty"`
	MailruSettings string `json:"mailruSettings,omitempty"`
	MicrosoftSettings string `json:"microsoftSettings,omitempty"`
	PublicIP string `json:"publicIP,omitempty"`
	QqSettings string `json:"qqSettings,omitempty"`
	ReverseDNSHostname string `json:"reverseDNSHostname,omitempty"`
	SystemDomain *ModelsSystemDomain `json:"systemDomain,omitempty"`
	Type_ *ModelsIpType `json:"type,omitempty"`
	YahooSettings string `json:"yahooSettings,omitempty"`
	YandexSettings string `json:"yandexSettings,omitempty"`
	ZohoSettings string `json:"zohoSettings,omitempty"`
}
